FROM nimlang/nim:alpine

RUN apk update
RUN apk add bash git pcre-dev 

RUN git clone --depth 1 https://github.com/arturo-lang/arturo.git
RUN cd arturo && ./build.nims build --install --mode mini --log
RUN rm -rf arturo

ENV PATH="/root/.arturo/bin:${PATH}"

WORKDIR /home

ENTRYPOINT [ "/root/.arturo/bin/arturo" ]
